<?php 


return [

    [
      'name' => 'Villa Front Lake',
      'description' => 'Villa Front Lake is an unrivaled luxury residence on Lake Como. Featuring spectacular design and décor, panoramic views, and beautifully landscaped grounds, this historic, seven-bedroom villa offers an incomparable ambience of privacy and class, making it perhaps the finest vacation rental for family reunions or destination wedding guests on Comos exclusive shores.',
      'cover_image' => 'https://a0.muscache.com/im/pictures/25af7fb2-36a6-4446-a2dc-3a6f9710e63c.jpg?im_w=1200',
      'rooms' => '7',
      'beds' => '7',
      'bathrooms' => '7',
      'mq' => '150',
      'accomodation' => '14',
      'lat' => '?',
      'long' => '?',
      'address' => 'Frazione Maggianico, Como',
      'available' => true,
      'price' => '8602',
    ],
    [
      'name' => 'Skylinemilan',
      'description' => 'Vivi lo spirito milanese più trendy in questo strepitoso attico dalle linee contemporane e materiali pregiati, dotato di bagno turco e di una enorme terrazza con vista sullo skyline di Milano che saprà stupirti: un ambiente di puro design contemporaneo con pareti e pavimento in legno, jacuzzi, doccia, veranda, piattaforma panoramica a 360°, uno scooter Lambretta  e una Jeep fuoristrada verde.',
      'cover_image' => 'https://a0.muscache.com/im/pictures/monet/Select-13797755/original/da8bc354-64e3-4620-b044-35c5b9df964d?im_w=1200',
      'rooms' => '2',
      'beds' => '2',
      'bathrooms' => '3',
      'mq' => '150',
      'accomodation' => '6',
      'lat' => '?',
      'long' => '?',
      'address' => 'Corso Como, Milano',
      'available' => true,
      'price' => '500',
    ],
    [
      'name' => 'Lussuoso. Vista incantevole.',
      'description' => 'Appartamento a picco sul lago, nuovo e lussuoso, in residence con piscina aperta nel periodo estivo dal 7 giugno al 22 settembre, campo da tennis, campo bocce e parco. Vista straordinaria. Posto auto di proprietà. 150 metri dal centro del borgo medioevale di Riva di Solto. Trilocale + bagno + 2 terrazzi.',
      'cover_image' => 'https://a0.muscache.com/im/pictures/53992414/64510035_original.jpg?im_w=1200',
      'rooms' => '2',
      'beds' => '6',
      'bathrooms' => '1',
      'mq' => '100',
      'accomodation' => '6',
      'lat' => '?',
      'long' => '?',
      'address' => 'Via S. Cassiano, Riva',
      'available' => true,
      'price' => '100',
    ],
    [
      'name' => 'Villa Il Cigno sul lago',
      'description' => 'Villa Il Cigno si trova direttamente sulle spettacolari rive del lago di Como affacciata su  un paesaggio unico delle Alpi e stupisce a prima vista per le sue imponenti dimensioni e il suo fascino.
      La proprietà fronte lago è ideale per chi ama il lusso e la vita al massimo con un lussureggiante parco ampio e rilassante su cui si affacciano alberi secolari.  
      Per goderti il tuo soggiorno puoi fare direttamente un giro in kayak o noleggiare una barca che ti verrà a prendere direttamente in casa.',
      'cover_image' => 'https://a0.muscache.com/im/pictures/74fe16d9-5712-4228-b5c6-165e9f3802a3.jpg?im_w=1200',
      'rooms' => '6',
      'beds' => '6',
      'bathrooms' => '4',
      'mq' => '333',
      'accomodation' => '10',
      'lat' => '?',
      'long' => '?',
      'address' => 'Via S. Cassiano, Riva',
      'available' => true,
      'price' => '1150',
    ],
    [
      'name' => 'La Finestra sul Lago',
      'description' => 'Tranquillità, eleganza, comodità e vicinanza alle più esclusive location del lago di Como: queste le parole ordine per una fuga dal caos cittadino e un tuffo in quella pace che solo un simile panorama di incontaminata bellezza è in grado di trasmettere',
      'cover_image' => 'https://a0.muscache.com/im/pictures/d37c749b-0c22-474d-a460-a83f4cbd1a9b.jpg?im_w=1200',
      'rooms' => '1',
      'beds' => '3',
      'bathrooms' => '1',
      'mq' => '60',
      'accomodation' => '10',
      'lat' => '?',
      'long' => '?',
      'address' => 'Via Dionigi, Limonta',
      'available' => true,
      'price' => '80',
    ],
    [
      'name' => 'Bellagio Bellavista di Betty',
      'description' => 'Dimentica ogni preoccupazione in questa ampia oasi di serenità. Totalmente immerso nella natura a ridosso del bosco dove spesso si possono vedere caprioli scoiattoli volpi e falchi. Splendida vista mozzafiato sul lago di Como e sulle Montagne Le Grigne, parcheggio privato, e giardino utilizzabile. Un open space completamente a tua disposizione.',
      'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-50042378/original/7556b2f2-5f19-48a2-96df-dc6097d2fcec.jpeg?im_w=1200',
      'rooms' => '1',
      'beds' => '2',
      'bathrooms' => '1',
      'mq' => '100',
      'accomodation' => '3',
      'lat' => '?',
      'long' => '?',
      'address' => 'Via Prà del calice, Civenna',
      'available' => true,
      'price' => '90',
    ],
    [
      'name' => 'Il rifugio dello scrittore villa lago',
      'description' => 'Un luogo esclusivo per godersi il fascino di una storia secolare. Un angolo riservato, dove poter godere di momenti unici di benessere, godersi la tranquillità del lago e ascoltare il silenzio delle sue albe e tramonti',
      'cover_image' => 'https://a0.muscache.com/im/pictures/7a6541b1-2f44-4287-ae6f-4d06ee3f3978.jpg?im_w=1200',
      'rooms' => '4',
      'beds' => '3',
      'bathrooms' => '3',
      'mq' => '77',
      'accomodation' => '7',
      'lat' => '?',
      'long' => '?',
      'address' => 'Via Aldo Moro, Riva',
      'available' => true,
      'price' => '90',
    ],
    [
      'name' => 'Vista unica sul Lago Maggiore, terrazza a 360°',
      'description' => 'Appartamento con fascino e vista direttamente sul Lago Maggiore, in Italia, Ascona e Locarno. l\'appartamento ha due terrazze panoramiche e un parcheggio, Comodo da solo in coppia',
      'cover_image' => 'https://a0.muscache.com/im/pictures/ebcbeba0-aa96-48f1-a658-39f57426008e.jpg?im_w=1200',
      'rooms' => '1',
      'beds' => '2',
      'bathrooms' => '2',
      'mq' => '77',
      'accomodation' => '2',
      'lat' => '?',
      'long' => '?',
      'address' => 'Via Bellavista, Ticino',
      'available' => true,
      'price' => '190',
    ],

]



?>